name: mlops-iris
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - numpy
  - matplotlib
  - seaborn
  - pip
  - pip:
    - azureml-sdk
    - azureml-mlflow
    - mlflow